# .github/workflows/build_database.yml

name: Build and Commit Product Database

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-db:
    # --- ADD THIS LINE ---
    # This prevents the workflow from running on its own commits.
    if: "!contains(github.event.head_commit.message, 'Automated:')"

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl

      - name: Run Data Ingestion Script
        run: python ingest_data.py

      - name: Commit and Push Database
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add products.db
          
          if ! git diff --staged --quiet; then
            # The commit message now includes "Automated:" which the 'if' condition above will catch
            git commit -m "Automated: Update product database"
            git pull origin main
            git push
          else
            echo "No changes to the database. Skipping commit."
          fi
